# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CTMediator' do

pod "HandyFrame"
pod repo add PrivatePods https://github.com/ModulizationDemo/PrivatePods.git
# pod "CTHandyCategories"

end

